def run():
  print("Please enter a character for the eye")
  eye = input()
  print("Beep's expression is now as follows:")
  print("          _____            ")
  print("         /_____\           ")
  print("    ____[\\" + eye+ "---" +eye +"/]____      ")
  print("   /\ #\ \_____/ /# /\     ")
  print("  /  \# \_.---._/ #/  \    ")
  print(" /   /|\  |   |  /|\   \   ")
  print("/___/ | | |   | | | \___\  ")
  print("|  |  | | |---| | |  |  |  ")
  print("|__|  \_| |_#_| |_/  |__|  ")
  print("//\\\\  <\ _//^\\\_ />  //\\\\  ")
  print("\||/  |\//// \\\\\\\/|  \||/  ")
  print("      |   |   |   |        ")
  print("      |---|   |---|        ")
  print("      |---|   |---|        ")
  print("      |   |   |   |        ")
  print("      |___|   |___|        ")
  print("      /   \   /   \        ")
  print("     |_____| |_____|       ")
  print("     |HHHHH| |HHHHH|       ")